format = """
[â–‘â–’â–“](white)\
$username\
[î‚°](bg:blue fg:white)\
$directory\
[î‚°](fg:blue bg:cyan)\
$git_branch\
$git_status\
$git_state\
[î‚°](fg:cyan bg:bright-black)\
$cmd_duration\
[î‚° ](fg:bright-black)\
\n$character"""

[character]
success_symbol = ' [âœ](bold green)'
error_symbol = ' [âœ—](bold red)'

[username]
style_user = 'bg:white fg:bright-black'
style_root = 'bg:white fg:bright-red'
format = '[ $user ]($style)'
show_always = true

[directory]
read_only = "ğŸ”’"
read_only_style = "fg:bright-red bg:blue"
style = "fg:white bg:blue"
truncation_length = 10
before_repo_root_style = "fg:white bg:blue"
repo_root_style = "fg:white bold bg:blue"
format = "[ $path ]($style)[$read_only]($read_only_style)"
repo_root_format = "[ ï ]($style)[$repo_root]($repo_root_style)[$path ]($style)[$read_only]($read_only_style)"

[git_branch]
symbol = "ï˜"
style = "bg:cyan"
format = '[[ $symbol $branch ](fg:black bg:cyan)]($style)'

[git_status]
style = "bg:cyan"
conflicted = '=${count} '
ahead = 'â‡¡${count} '
behind = 'â‡£${count} '
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count} '
untracked = '?${count} '
stashed = 'ó°—${count} '
modified = '!${count} '
staged = '+${count} '
renamed = 'Â»${count} '
deleted = 'âœ˜${count} '
format = '[[($all_status$ahead_behind)](fg:black bg:cyan)]($style)'

[git_state]
style = "bg:cyan"       
format = '[[\($state( $progress_current of $progress_total)\)](fg:bright-white bg:cyan) ]($style)'

[cmd_duration]
min_time = 0
style = "bg:bright-black"
format = '[[ $duration ](fg:white bg:bright-black)]($style)'